const matches = [
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442948,
    utcDate: "2024-03-29T20:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 521,
      name: "Lille OSC",
      shortName: "Lille",
      tla: "LIL",
      crest: "https://crests.football-data.org/521.svg",
    },
    awayTeam: {
      id: 546,
      name: "Racing Club de Lens",
      shortName: "RC Lens",
      tla: "RCL",
      crest: "https://crests.football-data.org/546.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442944,
    utcDate: "2024-03-30T16:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 545,
      name: "FC Metz",
      shortName: "FC Metz",
      tla: "FCM",
      crest: "https://crests.football-data.org/545.svg",
    },
    awayTeam: {
      id: 548,
      name: "AS Monaco FC",
      shortName: "Monaco",
      tla: "ASM",
      crest: "https://crests.football-data.org/548.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442947,
    utcDate: "2024-03-30T20:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 523,
      name: "Olympique Lyonnais",
      shortName: "Olympique Lyon",
      tla: "LYO",
      crest: "https://crests.football-data.org/523.svg",
    },
    awayTeam: {
      id: 547,
      name: "Stade de Reims",
      shortName: "Stade de Reims",
      tla: "SDR",
      crest: "https://crests.football-data.org/547.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442943,
    utcDate: "2024-03-31T11:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 525,
      name: "FC Lorient",
      shortName: "Lorient",
      tla: "FCL",
      crest: "https://crests.football-data.org/525.png",
    },
    awayTeam: {
      id: 512,
      name: "Stade Brestois 29",
      shortName: "Brest",
      tla: "BRE",
      crest: "https://crests.football-data.org/512.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442941,
    utcDate: "2024-03-31T13:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 533,
      name: "Le Havre AC",
      shortName: "Le Havre",
      tla: "HAC",
      crest: "https://crests.football-data.org/533.png",
    },
    awayTeam: {
      id: 518,
      name: "Montpellier HSC",
      shortName: "Montpellier",
      tla: "MON",
      crest: "https://crests.football-data.org/518.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442942,
    utcDate: "2024-03-31T13:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 541,
      name: "Clermont Foot 63",
      shortName: "Clermont Foot",
      tla: "CLF",
      crest: "https://crests.football-data.org/541.svg",
    },
    awayTeam: {
      id: 511,
      name: "Toulouse FC",
      shortName: "Toulouse",
      tla: "TOU",
      crest: "https://crests.football-data.org/511.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442945,
    utcDate: "2024-03-31T13:00:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 522,
      name: "OGC Nice",
      shortName: "Nice",
      tla: "NIC",
      crest: "https://crests.football-data.org/522.png",
    },
    awayTeam: {
      id: 543,
      name: "FC Nantes",
      shortName: "Nantes",
      tla: "NAN",
      crest: "https://crests.football-data.org/543.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442949,
    utcDate: "2024-03-31T15:05:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 576,
      name: "RC Strasbourg Alsace",
      shortName: "Strasbourg",
      tla: "RC ",
      crest: "https://crests.football-data.org/576.png",
    },
    awayTeam: {
      id: 529,
      name: "Stade Rennais FC 1901",
      shortName: "Stade Rennais",
      tla: "REN",
      crest: "https://crests.football-data.org/529.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442946,
    utcDate: "2024-03-31T18:45:00Z",
    status: "TIMED",
    matchday: 27,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-10T05:21:21Z",
    homeTeam: {
      id: 516,
      name: "Olympique de Marseille",
      shortName: "Marseille",
      tla: "MAR",
      crest: "https://crests.football-data.org/516.png",
    },
    awayTeam: {
      id: 524,
      name: "Paris Saint-Germain FC",
      shortName: "PSG",
      tla: "PSG",
      crest: "https://crests.football-data.org/524.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442954,
    utcDate: "2024-04-05T19:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-19T15:21:36Z",
    homeTeam: {
      id: 521,
      name: "Lille OSC",
      shortName: "Lille",
      tla: "LIL",
      crest: "https://crests.football-data.org/521.svg",
    },
    awayTeam: {
      id: 516,
      name: "Olympique de Marseille",
      shortName: "Marseille",
      tla: "MAR",
      crest: "https://crests.football-data.org/516.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442956,
    utcDate: "2024-04-06T15:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-19T15:21:36Z",
    homeTeam: {
      id: 546,
      name: "Racing Club de Lens",
      shortName: "RC Lens",
      tla: "RCL",
      crest: "https://crests.football-data.org/546.png",
    },
    awayTeam: {
      id: 533,
      name: "Le Havre AC",
      shortName: "Le Havre",
      tla: "HAC",
      crest: "https://crests.football-data.org/533.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442955,
    utcDate: "2024-04-06T19:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-19T15:21:36Z",
    homeTeam: {
      id: 524,
      name: "Paris Saint-Germain FC",
      shortName: "PSG",
      tla: "PSG",
      crest: "https://crests.football-data.org/524.png",
    },
    awayTeam: {
      id: 541,
      name: "Clermont Foot 63",
      shortName: "Clermont Foot",
      tla: "CLF",
      crest: "https://crests.football-data.org/541.svg",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442957,
    utcDate: "2024-04-07T11:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-12T15:21:26Z",
    homeTeam: {
      id: 512,
      name: "Stade Brestois 29",
      shortName: "Brest",
      tla: "BRE",
      crest: "https://crests.football-data.org/512.png",
    },
    awayTeam: {
      id: 545,
      name: "FC Metz",
      shortName: "FC Metz",
      tla: "FCM",
      crest: "https://crests.football-data.org/545.svg",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442952,
    utcDate: "2024-04-07T13:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-12T15:21:26Z",
    homeTeam: {
      id: 511,
      name: "Toulouse FC",
      shortName: "Toulouse",
      tla: "TOU",
      crest: "https://crests.football-data.org/511.png",
    },
    awayTeam: {
      id: 576,
      name: "RC Strasbourg Alsace",
      shortName: "Strasbourg",
      tla: "RC ",
      crest: "https://crests.football-data.org/576.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442953,
    utcDate: "2024-04-07T13:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-12T15:21:26Z",
    homeTeam: {
      id: 518,
      name: "Montpellier HSC",
      shortName: "Montpellier",
      tla: "MON",
      crest: "https://crests.football-data.org/518.png",
    },
    awayTeam: {
      id: 525,
      name: "FC Lorient",
      shortName: "Lorient",
      tla: "FCL",
      crest: "https://crests.football-data.org/525.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442958,
    utcDate: "2024-04-07T13:00:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-12T15:21:26Z",
    homeTeam: {
      id: 547,
      name: "Stade de Reims",
      shortName: "Stade de Reims",
      tla: "SDR",
      crest: "https://crests.football-data.org/547.png",
    },
    awayTeam: {
      id: 522,
      name: "OGC Nice",
      shortName: "Nice",
      tla: "NIC",
      crest: "https://crests.football-data.org/522.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442950,
    utcDate: "2024-04-07T15:05:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-19T15:21:36Z",
    homeTeam: {
      id: 548,
      name: "AS Monaco FC",
      shortName: "Monaco",
      tla: "ASM",
      crest: "https://crests.football-data.org/548.png",
    },
    awayTeam: {
      id: 529,
      name: "Stade Rennais FC 1901",
      shortName: "Stade Rennais",
      tla: "REN",
      crest: "https://crests.football-data.org/529.png",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
  {
    area: {
      id: 2081,
      name: "France",
      code: "FRA",
      flag: "https://crests.football-data.org/773.svg",
    },
    competition: {
      id: 2015,
      name: "Ligue 1",
      code: "FL1",
      type: "LEAGUE",
      emblem: "https://crests.football-data.org/FL1.png",
    },
    season: {
      id: 1595,
      startDate: "2023-08-13",
      endDate: "2024-05-18",
      currentMatchday: 27,
      winner: null,
    },
    id: 442951,
    utcDate: "2024-04-07T18:45:00Z",
    status: "TIMED",
    matchday: 28,
    stage: "REGULAR_SEASON",
    group: null,
    lastUpdated: "2024-03-19T15:21:36Z",
    homeTeam: {
      id: 543,
      name: "FC Nantes",
      shortName: "Nantes",
      tla: "NAN",
      crest: "https://crests.football-data.org/543.png",
    },
    awayTeam: {
      id: 523,
      name: "Olympique Lyonnais",
      shortName: "Olympique Lyon",
      tla: "LYO",
      crest: "https://crests.football-data.org/523.svg",
    },
    score: {
      winner: null,
      duration: "REGULAR",
      fullTime: {
        home: null,
        away: null,
      },
      halfTime: {
        home: null,
        away: null,
      },
    },
    odds: {
      msg: "Activate Odds-Package in User-Panel to retrieve odds.",
    },
    referees: [],
  },
];

// Set to store unique club names
const clubNamesSet = new Set();

// Iterate through each match and add home and away team names to the set
matches.forEach((match) => {
  clubNamesSet.add(match.homeTeam.name);
  clubNamesSet.add(match.awayTeam.name);
});

// Convert Set to array
const clubNamesArray = Array.from(clubNamesSet);

// Now you have an array of unique club names
console.log(clubNamesArray);
